
FactoryGirl.define do

  factory :solr_response, class: OpenStruct do
    skip_create

    response {
      {"responseHeader"=>
        {"status"=>0,
         "QTime"=>64,
         "params"=>
          {"q"=>"uid:\"doi:10.1234/5678\"",
           "tv"=>"true",
           "defType"=>"lucene",
           "fl"=>
            "uid,doi,license,license_url,data_source,authors,title,journal,year,volume,number,pages,fulltext_url,fulltext",
           "wt"=>"ruby"}},
       "response"=>
        {"numFound"=>1,
         "start"=>0,
         "docs"=>
          [{"uid"=>"doi:10.1234/5678",
            "doi"=>"10.1234/5678",
            "license"=>"Public domain",
            "data_source"=>"Test fixture",
            "license_url"=>"https://creativecommons.org/publicdomain/zero/1.0/",
            "authors"=>"A. One, B. Two",
            "title"=>"Test Title",
            "journal"=>"Journal",
            "year"=>"2010",
            "volume"=>"10",
            "number"=>"20",
            "pages"=>"100-200",
            "fulltext"=>
             "\n    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do\n    eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim\n    ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut\n    aliquip ex ea commodo consequat. Duis aute irure dolor in\n    reprehenderit in voluptate velit esse cillum dolore eu fugiat\n    nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt\n    in culpa qui officia deserunt mollit anim id est laborum.\n\n    Pellentesque habitant morbi tristique senectus et netus et malesuada\n    fames ac turpis egestas. Aliquam erat volutpat. In facilisis bibendum\n    tincidunt. Cras in ex sit amet dui pulvinar blandit aliquam vitae\n    risus. Curabitur commodo nibh ex, in tincidunt diam porta at. Proin\n    euismod at leo a faucibus. Quisque sagittis facilisis malesuada.\n    Quisque efficitur quis lacus eget finibus. Nulla facilisi.\n    Suspendisse pharetra turpis vitae odio placerat consequat. Nunc at\n    pulvinar risus, at rutrum sem. Ut fringilla mauris quam. Aenean\n    mollis congue arcu, sodales lacinia risus facilisis in.\n\n    Cum sociis natoque penatibus et magnis dis parturient montes,\n    nascetur ridiculus mus. Suspendisse auctor lectus sit amet egestas\n    consequat. Ut nec varius magna. Vivamus non feugiat ligula, eu\n    vulputate lorem. Duis nulla nisi, fringilla a sollicitudin sed,\n    fringilla eu urna. Fusce porta nulla libero, volutpat pharetra\n    sapien gravida sed. Proin sed dictum sapien, in feugiat ex.\n    Suspendisse vel massa congue, congue orci ut, luctus leo. Cras eu\n    dapibus arcu, quis sollicitudin dolor. Cras vitae volutpat quam, in\n    vulputate ante. Nulla pharetra diam convallis molestie venenatis. Sed\n    luctus condimentum erat sed fringilla.\n\n    Nunc efficitur diam et tortor fermentum, quis tincidunt ante\n    vehicula. Duis sagittis eros egestas interdum pulvinar. Praesent ut\n    massa a purus iaculis lacinia non sed nisi. Suspendisse ac sapien eu\n    mi egestas auctor sed eu nunc. Morbi viverra sem vestibulum, eleifend\n    odio ac, rutrum dolor. Nulla eu sapien a tellus porttitor vestibulum.\n    Phasellus tincidunt sapien molestie ligula lobortis maximus. Nullam\n    sed maximus diam. Proin viverra sem vel enim dignissim rutrum. Nullam\n    nec suscipit nibh, et feugiat mauris. Phasellus bibendum ut erat id\n    pretium.\n\n    Mauris et maximus nunc. Nullam justo est, laoreet nec orci et,\n    lobortis congue velit. Sed arcu neque, mattis vel tincidunt sit amet,\n    semper at sapien. Sed ornare metus magna, nec scelerisque leo varius\n    sed. In sem eros, pretium ac viverra a, ultrices et augue.\n    Pellentesque purus nunc, rutrum ac mi vitae, porttitor pretium ex.\n    Nam mi erat, ultrices sed metus non, maximus molestie dui.\n    Suspendisse elit purus, sollicitudin eget turpis a, sollicitudin\n    ornare nulla. Sed dapibus mauris suscipit velit mattis, in finibus\n    turpis mattis. Curabitur nisl purus, dictum a arcu nec, vehicula\n    ultrices leo. Maecenas elit tellus, mollis a urna in, rhoncus\n    hendrerit nunc. Curabitur bibendum velit vitae ante lobortis\n    sagittis. Aliquam tincidunt elit vel nulla convallis cursus.\n  ",
            "term_vectors"=>
             {"a"=>
               {"tf"=>8,
                "positions"=>[113, 188, 264, 293, 368, 398, 416, 426],
                "df"=>1.0},
              "ac"=>{"tf"=>5, "positions"=>[79, 272, 287, 366, 376], "df"=>1.0},
              "ad"=>{"tf"=>1, "positions"=>[21], "df"=>1.0},
              "adipiscing"=>{"tf"=>1, "positions"=>[6], "df"=>1.0},
              "aenean"=>{"tf"=>1, "positions"=>[145], "df"=>1.0},
              "aliqua"=>{"tf"=>1, "positions"=>[18], "df"=>1.0},
              "aliquam"=>{"tf"=>3, "positions"=>[82, 97, 439], "df"=>1.0},
              "aliquip"=>{"tf"=>1, "positions"=>[31], "df"=>1.0},
              "amet"=>{"tf"=>4, "positions"=>[4, 93, 170, 349], "df"=>1.0},
              "anim"=>{"tf"=>1, "positions"=>[65], "df"=>1.0},
              "ante"=>{"tf"=>3, "positions"=>[232, 253, 436], "df"=>1.0},
              "arcu"=>{"tf"=>4, "positions"=>[148, 222, 343, 417], "df"=>1.0},
              "at"=>{"tf"=>5, "positions"=>[108, 111, 135, 138, 351], "df"=>1.0},
              "auctor"=>{"tf"=>2, "positions"=>[167, 277], "df"=>1.0},
              "augue"=>{"tf"=>1, "positions"=>[371], "df"=>1.0},
              "aute"=>{"tf"=>1, "positions"=>[37], "df"=>1.0},
              "bibendum"=>{"tf"=>3, "positions"=>[87, 323, 433], "df"=>1.0},
              "blandit"=>{"tf"=>1, "positions"=>[96], "df"=>1.0},
              "cillum"=>{"tf"=>1, "positions"=>[46], "df"=>1.0},
              "commodo"=>{"tf"=>2, "positions"=>[34, 101], "df"=>1.0},
              "condimentum"=>{"tf"=>1, "positions"=>[241], "df"=>1.0},
              "congue"=>{"tf"=>4, "positions"=>[147, 213, 214, 340], "df"=>1.0},
              "consectetur"=>{"tf"=>1, "positions"=>[5], "df"=>1.0},
              "consequat"=>{"tf"=>3, "positions"=>[35, 133, 172], "df"=>1.0},
              "convallis"=>{"tf"=>2, "positions"=>[236, 444], "df"=>1.0},
              "cras"=>{"tf"=>3, "positions"=>[89, 219, 226], "df"=>1.0},
              "culpa"=>{"tf"=>1, "positions"=>[60], "df"=>1.0},
              "cum"=>{"tf"=>1, "positions"=>[154], "df"=>1.0},
              "cupidatat"=>{"tf"=>1, "positions"=>[55], "df"=>1.0},
              "curabitur"=>{"tf"=>3, "positions"=>[100, 412, 432], "df"=>1.0},
              "cursus"=>{"tf"=>1, "positions"=>[445], "df"=>1.0},
              "dapibus"=>{"tf"=>2, "positions"=>[221, 403], "df"=>1.0},
              "deserunt"=>{"tf"=>1, "positions"=>[63], "df"=>1.0},
              "diam"=>{"tf"=>4, "positions"=>[106, 235, 247, 307], "df"=>1.0},
              "dictum"=>{"tf"=>2, "positions"=>[205, 415], "df"=>1.0},
              "dignissim"=>{"tf"=>1, "positions"=>[313], "df"=>1.0},
              "dis"=>{"tf"=>1, "positions"=>[160], "df"=>1.0},
              "do"=>{"tf"=>1, "positions"=>[9], "df"=>1.0},
              "dolor"=>{"tf"=>4, "positions"=>[2, 39, 225, 289], "df"=>1.0},
              "dolore"=>{"tf"=>2, "positions"=>[16, 47], "df"=>1.0},
              "dui"=>{"tf"=>2, "positions"=>[94, 391], "df"=>1.0},
              "duis"=>{"tf"=>3, "positions"=>[36, 184, 255], "df"=>1.0},
              "ea"=>{"tf"=>1, "positions"=>[33], "df"=>1.0},
              "efficitur"=>{"tf"=>2, "positions"=>[120, 246], "df"=>1.0},
              "egestas"=>{"tf"=>4, "positions"=>[81, 171, 258, 276], "df"=>1.0},
              "eget"=>{"tf"=>2, "positions"=>[123, 396], "df"=>1.0},
              "eiusmod"=>{"tf"=>1, "positions"=>[10], "df"=>1.0},
              "eleifend"=>{"tf"=>1, "positions"=>[285], "df"=>1.0},
              "elit"=>{"tf"=>4, "positions"=>[7, 393, 423, 441], "df"=>1.0},
              "enim"=>{"tf"=>2, "positions"=>[20, 312], "df"=>1.0},
              "erat"=>{"tf"=>4, "positions"=>[83, 242, 325, 384], "df"=>1.0},
              "eros"=>{"tf"=>2, "positions"=>[257, 364], "df"=>1.0},
              "esse"=>{"tf"=>1, "positions"=>[45], "df"=>1.0},
              "est"=>{"tf"=>2, "positions"=>[67, 334], "df"=>1.0},
              "et"=>
               {"tf"=>9,
                "positions"=>[15, 74, 76, 158, 248, 319, 329, 338, 370],
                "df"=>1.0},
              "eu"=>
               {"tf"=>7, "positions"=>[48, 181, 192, 220, 274, 279, 291], "df"=>1.0},
              "euismod"=>{"tf"=>1, "positions"=>[110], "df"=>1.0},
              "ex"=>{"tf"=>5, "positions"=>[32, 91, 103, 209, 381], "df"=>1.0},
              "excepteur"=>{"tf"=>1, "positions"=>[52], "df"=>1.0},
              "exercitation"=>{"tf"=>1, "positions"=>[26], "df"=>1.0},
              "facilisi"=>{"tf"=>1, "positions"=>[126], "df"=>1.0},
              "facilisis"=>{"tf"=>3, "positions"=>[86, 117, 152], "df"=>1.0},
              "fames"=>{"tf"=>1, "positions"=>[78], "df"=>1.0},
              "faucibus"=>{"tf"=>1, "positions"=>[114], "df"=>1.0},
              "fermentum"=>{"tf"=>1, "positions"=>[250], "df"=>1.0},
              "feugiat"=>{"tf"=>3, "positions"=>[179, 208, 320], "df"=>1.0},
              "finibus"=>{"tf"=>2, "positions"=>[124, 409], "df"=>1.0},
              "fringilla"=>{"tf"=>4, "positions"=>[142, 187, 191, 244], "df"=>1.0},
              "fugiat"=>{"tf"=>1, "positions"=>[49], "df"=>1.0},
              "fusce"=>{"tf"=>1, "positions"=>[194], "df"=>1.0},
              "gravida"=>{"tf"=>1, "positions"=>[201], "df"=>1.0},
              "habitant"=>{"tf"=>1, "positions"=>[70], "df"=>1.0},
              "hendrerit"=>{"tf"=>1, "positions"=>[430], "df"=>1.0},
              "iaculis"=>{"tf"=>1, "positions"=>[266], "df"=>1.0},
              "id"=>{"tf"=>2, "positions"=>[66, 326], "df"=>1.0},
              "in"=>
               {"tf"=>12,
                "positions"=>[40, 42, 59, 85, 90, 104, 153, 207, 230, 362, 408, 428],
                "df"=>1.0},
              "incididunt"=>{"tf"=>1, "positions"=>[12], "df"=>1.0},
              "interdum"=>{"tf"=>1, "positions"=>[259], "df"=>1.0},
              "ipsum"=>{"tf"=>1, "positions"=>[1], "df"=>1.0},
              "irure"=>{"tf"=>1, "positions"=>[38], "df"=>1.0},
              "justo"=>{"tf"=>1, "positions"=>[333], "df"=>1.0},
              "labore"=>{"tf"=>1, "positions"=>[14], "df"=>1.0},
              "laboris"=>{"tf"=>1, "positions"=>[28], "df"=>1.0},
              "laborum"=>{"tf"=>1, "positions"=>[68], "df"=>1.0},
              "lacinia"=>{"tf"=>2, "positions"=>[150, 267], "df"=>1.0},
              "lacus"=>{"tf"=>1, "positions"=>[122], "df"=>1.0},
              "laoreet"=>{"tf"=>1, "positions"=>[335], "df"=>1.0},
              "lectus"=>{"tf"=>1, "positions"=>[168], "df"=>1.0},
              "leo"=>{"tf"=>4, "positions"=>[112, 218, 359, 421], "df"=>1.0},
              "libero"=>{"tf"=>1, "positions"=>[197], "df"=>1.0},
              "ligula"=>{"tf"=>2, "positions"=>[180, 301], "df"=>1.0},
              "lobortis"=>{"tf"=>3, "positions"=>[302, 339, 437], "df"=>1.0},
              "lorem"=>{"tf"=>2, "positions"=>[0, 183], "df"=>1.0},
              "luctus"=>{"tf"=>2, "positions"=>[217, 240], "df"=>1.0},
              "maecenas"=>{"tf"=>1, "positions"=>[422], "df"=>1.0},
              "magna"=>{"tf"=>3, "positions"=>[17, 176, 356], "df"=>1.0},
              "magnis"=>{"tf"=>1, "positions"=>[159], "df"=>1.0},
              "malesuada"=>{"tf"=>2, "positions"=>[77, 118], "df"=>1.0},
              "massa"=>{"tf"=>2, "positions"=>[212, 263], "df"=>1.0},
              "mattis"=>{"tf"=>3, "positions"=>[345, 407, 411], "df"=>1.0},
              "mauris"=>{"tf"=>4, "positions"=>[143, 321, 328, 404], "df"=>1.0},
              "maximus"=>{"tf"=>4, "positions"=>[303, 306, 330, 389], "df"=>1.0},
              "metus"=>{"tf"=>2, "positions"=>[355, 387], "df"=>1.0},
              "mi"=>{"tf"=>3, "positions"=>[275, 377, 383], "df"=>1.0},
              "minim"=>{"tf"=>1, "positions"=>[22], "df"=>1.0},
              "molestie"=>{"tf"=>3, "positions"=>[237, 300, 390], "df"=>1.0},
              "mollis"=>{"tf"=>2, "positions"=>[146, 425], "df"=>1.0},
              "mollit"=>{"tf"=>1, "positions"=>[64], "df"=>1.0},
              "montes"=>{"tf"=>1, "positions"=>[162], "df"=>1.0},
              "morbi"=>{"tf"=>2, "positions"=>[71, 281], "df"=>1.0},
              "mus"=>{"tf"=>1, "positions"=>[165], "df"=>1.0},
              "nam"=>{"tf"=>1, "positions"=>[382], "df"=>1.0},
              "nascetur"=>{"tf"=>1, "positions"=>[163], "df"=>1.0},
              "natoque"=>{"tf"=>1, "positions"=>[156], "df"=>1.0},
              "nec"=>{"tf"=>5, "positions"=>[174, 316, 336, 357, 418], "df"=>1.0},
              "neque"=>{"tf"=>1, "positions"=>[344], "df"=>1.0},
              "netus"=>{"tf"=>1, "positions"=>[75], "df"=>1.0},
              "nibh"=>{"tf"=>2, "positions"=>[102, 318], "df"=>1.0},
              "nisi"=>{"tf"=>3, "positions"=>[29, 186, 270], "df"=>1.0},
              "nisl"=>{"tf"=>1, "positions"=>[413], "df"=>1.0},
              "non"=>{"tf"=>4, "positions"=>[56, 178, 268, 388], "df"=>1.0},
              "nostrud"=>{"tf"=>1, "positions"=>[25], "df"=>1.0},
              "nulla"=>
               {"tf"=>8,
                "positions"=>[50, 125, 185, 196, 233, 290, 401, 443],
                "df"=>1.0},
              "nullam"=>{"tf"=>3, "positions"=>[304, 315, 332], "df"=>1.0},
              "nunc"=>
               {"tf"=>6, "positions"=>[134, 245, 280, 331, 374, 431], "df"=>1.0},
              "occaecat"=>{"tf"=>1, "positions"=>[54], "df"=>1.0},
              "odio"=>{"tf"=>2, "positions"=>[131, 286], "df"=>1.0},
              "officia"=>{"tf"=>1, "positions"=>[62], "df"=>1.0},
              "orci"=>{"tf"=>2, "positions"=>[215, 337], "df"=>1.0},
              "ornare"=>{"tf"=>2, "positions"=>[354, 400], "df"=>1.0},
              "pariatur"=>{"tf"=>1, "positions"=>[51], "df"=>1.0},
              "parturient"=>{"tf"=>1, "positions"=>[161], "df"=>1.0},
              "pellentesque"=>{"tf"=>2, "positions"=>[69, 372], "df"=>1.0},
              "penatibus"=>{"tf"=>1, "positions"=>[157], "df"=>1.0},
              "pharetra"=>{"tf"=>3, "positions"=>[128, 199, 234], "df"=>1.0},
              "phasellus"=>{"tf"=>2, "positions"=>[297, 322], "df"=>1.0},
              "placerat"=>{"tf"=>1, "positions"=>[132], "df"=>1.0},
              "porta"=>{"tf"=>2, "positions"=>[107, 195], "df"=>1.0},
              "porttitor"=>{"tf"=>2, "positions"=>[295, 379], "df"=>1.0},
              "praesent"=>{"tf"=>1, "positions"=>[261], "df"=>1.0},
              "pretium"=>{"tf"=>3, "positions"=>[327, 365, 380], "df"=>1.0},
              "proident"=>{"tf"=>1, "positions"=>[57], "df"=>1.0},
              "proin"=>{"tf"=>3, "positions"=>[109, 203, 308], "df"=>1.0},
              "pulvinar"=>{"tf"=>3, "positions"=>[95, 136, 260], "df"=>1.0},
              "purus"=>{"tf"=>4, "positions"=>[265, 373, 394, 414], "df"=>1.0},
              "quam"=>{"tf"=>2, "positions"=>[144, 229], "df"=>1.0},
              "qui"=>{"tf"=>1, "positions"=>[61], "df"=>1.0},
              "quis"=>{"tf"=>4, "positions"=>[24, 121, 223, 251], "df"=>1.0},
              "quisque"=>{"tf"=>2, "positions"=>[115, 119], "df"=>1.0},
              "reprehenderit"=>{"tf"=>1, "positions"=>[41], "df"=>1.0},
              "rhoncus"=>{"tf"=>1, "positions"=>[429], "df"=>1.0},
              "ridiculus"=>{"tf"=>1, "positions"=>[164], "df"=>1.0},
              "risus"=>{"tf"=>3, "positions"=>[99, 137, 151], "df"=>1.0},
              "rutrum"=>{"tf"=>4, "positions"=>[139, 288, 314, 375], "df"=>1.0},
              "sagittis"=>{"tf"=>3, "positions"=>[116, 256, 438], "df"=>1.0},
              "sapien"=>
               {"tf"=>6, "positions"=>[200, 206, 273, 292, 299, 352], "df"=>1.0},
              "scelerisque"=>{"tf"=>1, "positions"=>[358], "df"=>1.0},
              "sed"=>
               {"tf"=>14,
                "positions"=>
                 [8,
                  190,
                  202,
                  204,
                  239,
                  243,
                  269,
                  278,
                  305,
                  342,
                  353,
                  361,
                  386,
                  402],
                "df"=>1.0},
              "sem"=>{"tf"=>4, "positions"=>[140, 283, 310, 363], "df"=>1.0},
              "semper"=>{"tf"=>1, "positions"=>[350], "df"=>1.0},
              "senectus"=>{"tf"=>1, "positions"=>[73], "df"=>1.0},
              "sint"=>{"tf"=>1, "positions"=>[53], "df"=>1.0},
              "sit"=>{"tf"=>4, "positions"=>[3, 92, 169, 348], "df"=>1.0},
              "sociis"=>{"tf"=>1, "positions"=>[155], "df"=>1.0},
              "sodales"=>{"tf"=>1, "positions"=>[149], "df"=>1.0},
              "sollicitudin"=>
               {"tf"=>4, "positions"=>[189, 224, 395, 399], "df"=>1.0},
              "sunt"=>{"tf"=>1, "positions"=>[58], "df"=>1.0},
              "suscipit"=>{"tf"=>2, "positions"=>[317, 405], "df"=>1.0},
              "suspendisse"=>
               {"tf"=>5, "positions"=>[127, 166, 210, 271, 392], "df"=>1.0},
              "tellus"=>{"tf"=>2, "positions"=>[294, 424], "df"=>1.0},
              "tempor"=>{"tf"=>1, "positions"=>[11], "df"=>1.0},
              "tincidunt"=>
               {"tf"=>6, "positions"=>[88, 105, 252, 298, 347, 440], "df"=>1.0},
              "tortor"=>{"tf"=>1, "positions"=>[249], "df"=>1.0},
              "tristique"=>{"tf"=>1, "positions"=>[72], "df"=>1.0},
              "turpis"=>{"tf"=>4, "positions"=>[80, 129, 397, 410], "df"=>1.0},
              "ullamco"=>{"tf"=>1, "positions"=>[27], "df"=>1.0},
              "ultrices"=>{"tf"=>3, "positions"=>[369, 385, 420], "df"=>1.0},
              "urna"=>{"tf"=>2, "positions"=>[193, 427], "df"=>1.0},
              "ut"=>
               {"tf"=>8,
                "positions"=>[13, 19, 30, 141, 173, 216, 262, 324],
                "df"=>1.0},
              "varius"=>{"tf"=>2, "positions"=>[175, 360], "df"=>1.0},
              "vehicula"=>{"tf"=>2, "positions"=>[254, 419], "df"=>1.0},
              "vel"=>{"tf"=>4, "positions"=>[211, 311, 346, 442], "df"=>1.0},
              "velit"=>{"tf"=>4, "positions"=>[44, 341, 406, 434], "df"=>1.0},
              "venenatis"=>{"tf"=>1, "positions"=>[238], "df"=>1.0},
              "veniam"=>{"tf"=>1, "positions"=>[23], "df"=>1.0},
              "vestibulum"=>{"tf"=>2, "positions"=>[284, 296], "df"=>1.0},
              "vitae"=>{"tf"=>5, "positions"=>[98, 130, 227, 378, 435], "df"=>1.0},
              "vivamus"=>{"tf"=>1, "positions"=>[177], "df"=>1.0},
              "viverra"=>{"tf"=>3, "positions"=>[282, 309, 367], "df"=>1.0},
              "voluptate"=>{"tf"=>1, "positions"=>[43], "df"=>1.0},
              "volutpat"=>{"tf"=>3, "positions"=>[84, 198, 228], "df"=>1.0},
              "vulputate"=>{"tf"=>2, "positions"=>[182, 231], "df"=>1.0}}}]},
       "facet_counts"=>
        {"facet_queries"=>
          {"year:[* TO 1799]"=>0,
           "year:[1800 TO 1809]"=>0,
           "year:[1810 TO 1819]"=>0,
           "year:[1820 TO 1829]"=>0,
           "year:[1830 TO 1839]"=>0,
           "year:[1840 TO 1849]"=>0,
           "year:[1850 TO 1859]"=>0,
           "year:[1860 TO 1869]"=>0,
           "year:[1870 TO 1879]"=>0,
           "year:[1880 TO 1889]"=>0,
           "year:[1890 TO 1899]"=>0,
           "year:[1900 TO 1909]"=>0,
           "year:[1910 TO 1919]"=>0,
           "year:[1920 TO 1929]"=>0,
           "year:[1930 TO 1939]"=>0,
           "year:[1940 TO 1949]"=>0,
           "year:[1950 TO 1959]"=>0,
           "year:[1960 TO 1969]"=>0,
           "year:[1970 TO 1979]"=>0,
           "year:[1980 TO 1989]"=>0,
           "year:[1990 TO 1999]"=>0,
           "year:[2000 TO 2009]"=>0,
           "year:[2010 TO *]"=>1},
         "facet_fields"=>
          {"authors_facet"=>["A. One", 1, "B. Two", 1],
           "journal_facet"=>["Journal", 1]},
         "facet_dates"=>{},
         "facet_ranges"=>{}},
       "termVectors"=>
        ["uniqueKeyFieldName",
         "uid",
         "doi:10.1234/5678",
         ["uniqueKey",
          "doi:10.1234/5678",
          "fulltext",
          ["a",
           ["tf",
            8,
            "positions",
            ["position",
             113,
             "position",
             188,
             "position",
             264,
             "position",
             293,
             "position",
             368,
             "position",
             398,
             "position",
             416,
             "position",
             426],
            "df",
            1],
           "ac",
           ["tf",
            5,
            "positions",
            ["position",
             79,
             "position",
             272,
             "position",
             287,
             "position",
             366,
             "position",
             376],
            "df",
            1],
           "ad",
           ["tf", 1, "positions", ["position", 21], "df", 1],
           "adipiscing",
           ["tf", 1, "positions", ["position", 6], "df", 1],
           "aenean",
           ["tf", 1, "positions", ["position", 145], "df", 1],
           "aliqua",
           ["tf", 1, "positions", ["position", 18], "df", 1],
           "aliquam",
           ["tf",
            3,
            "positions",
            ["position", 82, "position", 97, "position", 439],
            "df",
            1],
           "aliquip",
           ["tf", 1, "positions", ["position", 31], "df", 1],
           "amet",
           ["tf",
            4,
            "positions",
            ["position", 4, "position", 93, "position", 170, "position", 349],
            "df",
            1],
           "anim",
           ["tf", 1, "positions", ["position", 65], "df", 1],
           "ante",
           ["tf",
            3,
            "positions",
            ["position", 232, "position", 253, "position", 436],
            "df",
            1],
           "arcu",
           ["tf",
            4,
            "positions",
            ["position", 148, "position", 222, "position", 343, "position", 417],
            "df",
            1],
           "at",
           ["tf",
            5,
            "positions",
            ["position",
             108,
             "position",
             111,
             "position",
             135,
             "position",
             138,
             "position",
             351],
            "df",
            1],
           "auctor",
           ["tf", 2, "positions", ["position", 167, "position", 277], "df", 1],
           "augue",
           ["tf", 1, "positions", ["position", 371], "df", 1],
           "aute",
           ["tf", 1, "positions", ["position", 37], "df", 1],
           "bibendum",
           ["tf",
            3,
            "positions",
            ["position", 87, "position", 323, "position", 433],
            "df",
            1],
           "blandit",
           ["tf", 1, "positions", ["position", 96], "df", 1],
           "cillum",
           ["tf", 1, "positions", ["position", 46], "df", 1],
           "commodo",
           ["tf", 2, "positions", ["position", 34, "position", 101], "df", 1],
           "condimentum",
           ["tf", 1, "positions", ["position", 241], "df", 1],
           "congue",
           ["tf",
            4,
            "positions",
            ["position", 147, "position", 213, "position", 214, "position", 340],
            "df",
            1],
           "consectetur",
           ["tf", 1, "positions", ["position", 5], "df", 1],
           "consequat",
           ["tf",
            3,
            "positions",
            ["position", 35, "position", 133, "position", 172],
            "df",
            1],
           "convallis",
           ["tf", 2, "positions", ["position", 236, "position", 444], "df", 1],
           "cras",
           ["tf",
            3,
            "positions",
            ["position", 89, "position", 219, "position", 226],
            "df",
            1],
           "culpa",
           ["tf", 1, "positions", ["position", 60], "df", 1],
           "cum",
           ["tf", 1, "positions", ["position", 154], "df", 1],
           "cupidatat",
           ["tf", 1, "positions", ["position", 55], "df", 1],
           "curabitur",
           ["tf",
            3,
            "positions",
            ["position", 100, "position", 412, "position", 432],
            "df",
            1],
           "cursus",
           ["tf", 1, "positions", ["position", 445], "df", 1],
           "dapibus",
           ["tf", 2, "positions", ["position", 221, "position", 403], "df", 1],
           "deserunt",
           ["tf", 1, "positions", ["position", 63], "df", 1],
           "diam",
           ["tf",
            4,
            "positions",
            ["position", 106, "position", 235, "position", 247, "position", 307],
            "df",
            1],
           "dictum",
           ["tf", 2, "positions", ["position", 205, "position", 415], "df", 1],
           "dignissim",
           ["tf", 1, "positions", ["position", 313], "df", 1],
           "dis",
           ["tf", 1, "positions", ["position", 160], "df", 1],
           "do",
           ["tf", 1, "positions", ["position", 9], "df", 1],
           "dolor",
           ["tf",
            4,
            "positions",
            ["position", 2, "position", 39, "position", 225, "position", 289],
            "df",
            1],
           "dolore",
           ["tf", 2, "positions", ["position", 16, "position", 47], "df", 1],
           "dui",
           ["tf", 2, "positions", ["position", 94, "position", 391], "df", 1],
           "duis",
           ["tf",
            3,
            "positions",
            ["position", 36, "position", 184, "position", 255],
            "df",
            1],
           "ea",
           ["tf", 1, "positions", ["position", 33], "df", 1],
           "efficitur",
           ["tf", 2, "positions", ["position", 120, "position", 246], "df", 1],
           "egestas",
           ["tf",
            4,
            "positions",
            ["position", 81, "position", 171, "position", 258, "position", 276],
            "df",
            1],
           "eget",
           ["tf", 2, "positions", ["position", 123, "position", 396], "df", 1],
           "eiusmod",
           ["tf", 1, "positions", ["position", 10], "df", 1],
           "eleifend",
           ["tf", 1, "positions", ["position", 285], "df", 1],
           "elit",
           ["tf",
            4,
            "positions",
            ["position", 7, "position", 393, "position", 423, "position", 441],
            "df",
            1],
           "enim",
           ["tf", 2, "positions", ["position", 20, "position", 312], "df", 1],
           "erat",
           ["tf",
            4,
            "positions",
            ["position", 83, "position", 242, "position", 325, "position", 384],
            "df",
            1],
           "eros",
           ["tf", 2, "positions", ["position", 257, "position", 364], "df", 1],
           "esse",
           ["tf", 1, "positions", ["position", 45], "df", 1],
           "est",
           ["tf", 2, "positions", ["position", 67, "position", 334], "df", 1],
           "et",
           ["tf",
            9,
            "positions",
            ["position",
             15,
             "position",
             74,
             "position",
             76,
             "position",
             158,
             "position",
             248,
             "position",
             319,
             "position",
             329,
             "position",
             338,
             "position",
             370],
            "df",
            1],
           "eu",
           ["tf",
            7,
            "positions",
            ["position",
             48,
             "position",
             181,
             "position",
             192,
             "position",
             220,
             "position",
             274,
             "position",
             279,
             "position",
             291],
            "df",
            1],
           "euismod",
           ["tf", 1, "positions", ["position", 110], "df", 1],
           "ex",
           ["tf",
            5,
            "positions",
            ["position",
             32,
             "position",
             91,
             "position",
             103,
             "position",
             209,
             "position",
             381],
            "df",
            1],
           "excepteur",
           ["tf", 1, "positions", ["position", 52], "df", 1],
           "exercitation",
           ["tf", 1, "positions", ["position", 26], "df", 1],
           "facilisi",
           ["tf", 1, "positions", ["position", 126], "df", 1],
           "facilisis",
           ["tf",
            3,
            "positions",
            ["position", 86, "position", 117, "position", 152],
            "df",
            1],
           "fames",
           ["tf", 1, "positions", ["position", 78], "df", 1],
           "faucibus",
           ["tf", 1, "positions", ["position", 114], "df", 1],
           "fermentum",
           ["tf", 1, "positions", ["position", 250], "df", 1],
           "feugiat",
           ["tf",
            3,
            "positions",
            ["position", 179, "position", 208, "position", 320],
            "df",
            1],
           "finibus",
           ["tf", 2, "positions", ["position", 124, "position", 409], "df", 1],
           "fringilla",
           ["tf",
            4,
            "positions",
            ["position", 142, "position", 187, "position", 191, "position", 244],
            "df",
            1],
           "fugiat",
           ["tf", 1, "positions", ["position", 49], "df", 1],
           "fusce",
           ["tf", 1, "positions", ["position", 194], "df", 1],
           "gravida",
           ["tf", 1, "positions", ["position", 201], "df", 1],
           "habitant",
           ["tf", 1, "positions", ["position", 70], "df", 1],
           "hendrerit",
           ["tf", 1, "positions", ["position", 430], "df", 1],
           "iaculis",
           ["tf", 1, "positions", ["position", 266], "df", 1],
           "id",
           ["tf", 2, "positions", ["position", 66, "position", 326], "df", 1],
           "in",
           ["tf",
            12,
            "positions",
            ["position",
             40,
             "position",
             42,
             "position",
             59,
             "position",
             85,
             "position",
             90,
             "position",
             104,
             "position",
             153,
             "position",
             207,
             "position",
             230,
             "position",
             362,
             "position",
             408,
             "position",
             428],
            "df",
            1],
           "incididunt",
           ["tf", 1, "positions", ["position", 12], "df", 1],
           "interdum",
           ["tf", 1, "positions", ["position", 259], "df", 1],
           "ipsum",
           ["tf", 1, "positions", ["position", 1], "df", 1],
           "irure",
           ["tf", 1, "positions", ["position", 38], "df", 1],
           "justo",
           ["tf", 1, "positions", ["position", 333], "df", 1],
           "labore",
           ["tf", 1, "positions", ["position", 14], "df", 1],
           "laboris",
           ["tf", 1, "positions", ["position", 28], "df", 1],
           "laborum",
           ["tf", 1, "positions", ["position", 68], "df", 1],
           "lacinia",
           ["tf", 2, "positions", ["position", 150, "position", 267], "df", 1],
           "lacus",
           ["tf", 1, "positions", ["position", 122], "df", 1],
           "laoreet",
           ["tf", 1, "positions", ["position", 335], "df", 1],
           "lectus",
           ["tf", 1, "positions", ["position", 168], "df", 1],
           "leo",
           ["tf",
            4,
            "positions",
            ["position", 112, "position", 218, "position", 359, "position", 421],
            "df",
            1],
           "libero",
           ["tf", 1, "positions", ["position", 197], "df", 1],
           "ligula",
           ["tf", 2, "positions", ["position", 180, "position", 301], "df", 1],
           "lobortis",
           ["tf",
            3,
            "positions",
            ["position", 302, "position", 339, "position", 437],
            "df",
            1],
           "lorem",
           ["tf", 2, "positions", ["position", 0, "position", 183], "df", 1],
           "luctus",
           ["tf", 2, "positions", ["position", 217, "position", 240], "df", 1],
           "maecenas",
           ["tf", 1, "positions", ["position", 422], "df", 1],
           "magna",
           ["tf",
            3,
            "positions",
            ["position", 17, "position", 176, "position", 356],
            "df",
            1],
           "magnis",
           ["tf", 1, "positions", ["position", 159], "df", 1],
           "malesuada",
           ["tf", 2, "positions", ["position", 77, "position", 118], "df", 1],
           "massa",
           ["tf", 2, "positions", ["position", 212, "position", 263], "df", 1],
           "mattis",
           ["tf",
            3,
            "positions",
            ["position", 345, "position", 407, "position", 411],
            "df",
            1],
           "mauris",
           ["tf",
            4,
            "positions",
            ["position", 143, "position", 321, "position", 328, "position", 404],
            "df",
            1],
           "maximus",
           ["tf",
            4,
            "positions",
            ["position", 303, "position", 306, "position", 330, "position", 389],
            "df",
            1],
           "metus",
           ["tf", 2, "positions", ["position", 355, "position", 387], "df", 1],
           "mi",
           ["tf",
            3,
            "positions",
            ["position", 275, "position", 377, "position", 383],
            "df",
            1],
           "minim",
           ["tf", 1, "positions", ["position", 22], "df", 1],
           "molestie",
           ["tf",
            3,
            "positions",
            ["position", 237, "position", 300, "position", 390],
            "df",
            1],
           "mollis",
           ["tf", 2, "positions", ["position", 146, "position", 425], "df", 1],
           "mollit",
           ["tf", 1, "positions", ["position", 64], "df", 1],
           "montes",
           ["tf", 1, "positions", ["position", 162], "df", 1],
           "morbi",
           ["tf", 2, "positions", ["position", 71, "position", 281], "df", 1],
           "mus",
           ["tf", 1, "positions", ["position", 165], "df", 1],
           "nam",
           ["tf", 1, "positions", ["position", 382], "df", 1],
           "nascetur",
           ["tf", 1, "positions", ["position", 163], "df", 1],
           "natoque",
           ["tf", 1, "positions", ["position", 156], "df", 1],
           "nec",
           ["tf",
            5,
            "positions",
            ["position",
             174,
             "position",
             316,
             "position",
             336,
             "position",
             357,
             "position",
             418],
            "df",
            1],
           "neque",
           ["tf", 1, "positions", ["position", 344], "df", 1],
           "netus",
           ["tf", 1, "positions", ["position", 75], "df", 1],
           "nibh",
           ["tf", 2, "positions", ["position", 102, "position", 318], "df", 1],
           "nisi",
           ["tf",
            3,
            "positions",
            ["position", 29, "position", 186, "position", 270],
            "df",
            1],
           "nisl",
           ["tf", 1, "positions", ["position", 413], "df", 1],
           "non",
           ["tf",
            4,
            "positions",
            ["position", 56, "position", 178, "position", 268, "position", 388],
            "df",
            1],
           "nostrud",
           ["tf", 1, "positions", ["position", 25], "df", 1],
           "nulla",
           ["tf",
            8,
            "positions",
            ["position",
             50,
             "position",
             125,
             "position",
             185,
             "position",
             196,
             "position",
             233,
             "position",
             290,
             "position",
             401,
             "position",
             443],
            "df",
            1],
           "nullam",
           ["tf",
            3,
            "positions",
            ["position", 304, "position", 315, "position", 332],
            "df",
            1],
           "nunc",
           ["tf",
            6,
            "positions",
            ["position",
             134,
             "position",
             245,
             "position",
             280,
             "position",
             331,
             "position",
             374,
             "position",
             431],
            "df",
            1],
           "occaecat",
           ["tf", 1, "positions", ["position", 54], "df", 1],
           "odio",
           ["tf", 2, "positions", ["position", 131, "position", 286], "df", 1],
           "officia",
           ["tf", 1, "positions", ["position", 62], "df", 1],
           "orci",
           ["tf", 2, "positions", ["position", 215, "position", 337], "df", 1],
           "ornare",
           ["tf", 2, "positions", ["position", 354, "position", 400], "df", 1],
           "pariatur",
           ["tf", 1, "positions", ["position", 51], "df", 1],
           "parturient",
           ["tf", 1, "positions", ["position", 161], "df", 1],
           "pellentesque",
           ["tf", 2, "positions", ["position", 69, "position", 372], "df", 1],
           "penatibus",
           ["tf", 1, "positions", ["position", 157], "df", 1],
           "pharetra",
           ["tf",
            3,
            "positions",
            ["position", 128, "position", 199, "position", 234],
            "df",
            1],
           "phasellus",
           ["tf", 2, "positions", ["position", 297, "position", 322], "df", 1],
           "placerat",
           ["tf", 1, "positions", ["position", 132], "df", 1],
           "porta",
           ["tf", 2, "positions", ["position", 107, "position", 195], "df", 1],
           "porttitor",
           ["tf", 2, "positions", ["position", 295, "position", 379], "df", 1],
           "praesent",
           ["tf", 1, "positions", ["position", 261], "df", 1],
           "pretium",
           ["tf",
            3,
            "positions",
            ["position", 327, "position", 365, "position", 380],
            "df",
            1],
           "proident",
           ["tf", 1, "positions", ["position", 57], "df", 1],
           "proin",
           ["tf",
            3,
            "positions",
            ["position", 109, "position", 203, "position", 308],
            "df",
            1],
           "pulvinar",
           ["tf",
            3,
            "positions",
            ["position", 95, "position", 136, "position", 260],
            "df",
            1],
           "purus",
           ["tf",
            4,
            "positions",
            ["position", 265, "position", 373, "position", 394, "position", 414],
            "df",
            1],
           "quam",
           ["tf", 2, "positions", ["position", 144, "position", 229], "df", 1],
           "qui",
           ["tf", 1, "positions", ["position", 61], "df", 1],
           "quis",
           ["tf",
            4,
            "positions",
            ["position", 24, "position", 121, "position", 223, "position", 251],
            "df",
            1],
           "quisque",
           ["tf", 2, "positions", ["position", 115, "position", 119], "df", 1],
           "reprehenderit",
           ["tf", 1, "positions", ["position", 41], "df", 1],
           "rhoncus",
           ["tf", 1, "positions", ["position", 429], "df", 1],
           "ridiculus",
           ["tf", 1, "positions", ["position", 164], "df", 1],
           "risus",
           ["tf",
            3,
            "positions",
            ["position", 99, "position", 137, "position", 151],
            "df",
            1],
           "rutrum",
           ["tf",
            4,
            "positions",
            ["position", 139, "position", 288, "position", 314, "position", 375],
            "df",
            1],
           "sagittis",
           ["tf",
            3,
            "positions",
            ["position", 116, "position", 256, "position", 438],
            "df",
            1],
           "sapien",
           ["tf",
            6,
            "positions",
            ["position",
             200,
             "position",
             206,
             "position",
             273,
             "position",
             292,
             "position",
             299,
             "position",
             352],
            "df",
            1],
           "scelerisque",
           ["tf", 1, "positions", ["position", 358], "df", 1],
           "sed",
           ["tf",
            14,
            "positions",
            ["position",
             8,
             "position",
             190,
             "position",
             202,
             "position",
             204,
             "position",
             239,
             "position",
             243,
             "position",
             269,
             "position",
             278,
             "position",
             305,
             "position",
             342,
             "position",
             353,
             "position",
             361,
             "position",
             386,
             "position",
             402],
            "df",
            1],
           "sem",
           ["tf",
            4,
            "positions",
            ["position", 140, "position", 283, "position", 310, "position", 363],
            "df",
            1],
           "semper",
           ["tf", 1, "positions", ["position", 350], "df", 1],
           "senectus",
           ["tf", 1, "positions", ["position", 73], "df", 1],
           "sint",
           ["tf", 1, "positions", ["position", 53], "df", 1],
           "sit",
           ["tf",
            4,
            "positions",
            ["position", 3, "position", 92, "position", 169, "position", 348],
            "df",
            1],
           "sociis",
           ["tf", 1, "positions", ["position", 155], "df", 1],
           "sodales",
           ["tf", 1, "positions", ["position", 149], "df", 1],
           "sollicitudin",
           ["tf",
            4,
            "positions",
            ["position", 189, "position", 224, "position", 395, "position", 399],
            "df",
            1],
           "sunt",
           ["tf", 1, "positions", ["position", 58], "df", 1],
           "suscipit",
           ["tf", 2, "positions", ["position", 317, "position", 405], "df", 1],
           "suspendisse",
           ["tf",
            5,
            "positions",
            ["position",
             127,
             "position",
             166,
             "position",
             210,
             "position",
             271,
             "position",
             392],
            "df",
            1],
           "tellus",
           ["tf", 2, "positions", ["position", 294, "position", 424], "df", 1],
           "tempor",
           ["tf", 1, "positions", ["position", 11], "df", 1],
           "tincidunt",
           ["tf",
            6,
            "positions",
            ["position",
             88,
             "position",
             105,
             "position",
             252,
             "position",
             298,
             "position",
             347,
             "position",
             440],
            "df",
            1],
           "tortor",
           ["tf", 1, "positions", ["position", 249], "df", 1],
           "tristique",
           ["tf", 1, "positions", ["position", 72], "df", 1],
           "turpis",
           ["tf",
            4,
            "positions",
            ["position", 80, "position", 129, "position", 397, "position", 410],
            "df",
            1],
           "ullamco",
           ["tf", 1, "positions", ["position", 27], "df", 1],
           "ultrices",
           ["tf",
            3,
            "positions",
            ["position", 369, "position", 385, "position", 420],
            "df",
            1],
           "urna",
           ["tf", 2, "positions", ["position", 193, "position", 427], "df", 1],
           "ut",
           ["tf",
            8,
            "positions",
            ["position",
             13,
             "position",
             19,
             "position",
             30,
             "position",
             141,
             "position",
             173,
             "position",
             216,
             "position",
             262,
             "position",
             324],
            "df",
            1],
           "varius",
           ["tf", 2, "positions", ["position", 175, "position", 360], "df", 1],
           "vehicula",
           ["tf", 2, "positions", ["position", 254, "position", 419], "df", 1],
           "vel",
           ["tf",
            4,
            "positions",
            ["position", 211, "position", 311, "position", 346, "position", 442],
            "df",
            1],
           "velit",
           ["tf",
            4,
            "positions",
            ["position", 44, "position", 341, "position", 406, "position", 434],
            "df",
            1],
           "venenatis",
           ["tf", 1, "positions", ["position", 238], "df", 1],
           "veniam",
           ["tf", 1, "positions", ["position", 23], "df", 1],
           "vestibulum",
           ["tf", 2, "positions", ["position", 284, "position", 296], "df", 1],
           "vitae",
           ["tf",
            5,
            "positions",
            ["position",
             98,
             "position",
             130,
             "position",
             227,
             "position",
             378,
             "position",
             435],
            "df",
            1],
           "vivamus",
           ["tf", 1, "positions", ["position", 177], "df", 1],
           "viverra",
           ["tf",
            3,
            "positions",
            ["position", 282, "position", 309, "position", 367],
            "df",
            1],
           "voluptate",
           ["tf", 1, "positions", ["position", 43], "df", 1],
           "volutpat",
           ["tf",
            3,
            "positions",
            ["position", 84, "position", 198, "position", 228],
            "df",
            1],
           "vulputate",
           ["tf", 2, "positions", ["position", 182, "position", 231], "df", 1]]
        ]
      ]}
    }
  end

end
