#!/bin/sh

curl -is "https://raw.github.com/citation-style-language/styles/master/science.csl" > csl_style_github.curl
curl -is "http://worldcatlibraries.org/registry/lookup?IP=255.255.255.254" > worldcat_no_libraries.curl
curl -is "http://worldcatlibraries.org/registry/lookup?IP=129.74.223.212" > worldcat_notre_dame.curl
curl -is "http://www.citeulike.org/json/search/all?page=1&per_page=1&q=title:(How%20Reliable%20are%20the%20Methods%20for%20Estimating%20Repertoire%20Size?)" > citeulike.curl
curl -is "http://api.mendeley.com/oapi/documents/search/title:How+Reliable+are+the+Methods+for+Estimating+Repertoire+Size%3F/?consumer_key=5ba3606d28aa1be94e9c58502b90a49c04dc17289" > mendeley.curl
