# -*- encoding : utf-8 -*-

# The array returned by Solr as response['termVectors']
def term_vector_solr_array
  ["uniqueKeyFieldName", "uid",
   "doi:10.1234/5678",
   ["uniqueKey", "doi:10.1234/5678",
    "fulltext",
    ["age",
     ["tf", 2,
      "positions", ["position", 15, "position", 21],
      "df", 1,
      "tf-idf", 2.0],
     "all",
     ["tf", 2,
      "positions", ["position", 72, "position", 79],
      "df", 1,
      "tf-idf", 2.0],
     "authorities",
     ["tf", 1,
      "positions", ["position", 101],
      "df", 1,
      "tf-idf", 1.0],
     "before",
     ["tf", 2,
      "positions", ["position", 63, "position", 68],
      "df", 1,
      "tf-idf", 2.0],
     "being",
     ["tf", 1,
      "positions", ["position", 105],
      "df", 1,
      "tf-idf", 1.0],
     "belief",
     ["tf", 1,
      "positions", ["position", 29],
      "df", 1,
      "tf-idf", 1.0],
     "best",
     ["tf", 1,
      "positions", ["position", 3],
      "df", 1,
      "tf-idf", 1.0],
     "comparison",
     ["tf", 1,
      "positions", ["position", 117],
      "df", 1,
      "tf-idf", 1.0],
     "darkness",
     ["tf", 1,
      "positions", ["position", 47],
      "df", 1,
      "tf-idf", 1.0],
     "degree",
     ["tf", 1,
      "positions", ["position", 115],
      "df", 1,
      "tf-idf", 1.0],
     "despair",
     ["tf", 1,
      "positions", ["position", 59],
      "df", 1,
      "tf-idf", 1.0],
     "direct",
     ["tf", 2,
      "positions", ["position", 74, "position", 81],
      "df", 1,
      "tf-idf", 2.0],
     "epoch",
     ["tf", 2,
      "positions", ["position", 27, "position", 33],
      "df", 1,
      "tf-idf", 2.0],
     "everything",
     ["tf", 1,
      "positions", ["position", 62],
      "df", 1,
      "tf-idf", 1.0],
     "evil",
     ["tf", 1,
      "positions", ["position", 111],
      "df", 1,
      "tf-idf", 1.0],
     "far",
     ["tf", 1,
      "positions", ["position", 91],
      "df", 1,
      "tf-idf", 1.0],
     "foolishness",
     ["tf", 1,
      "positions", ["position", 23],
      "df", 1,
      "tf-idf", 1.0],
     "for",
     ["tf", 2,
      "positions", ["position", 107, "position", 110],
      "df", 1,
      "tf-idf", 2.0],
     "going",
     ["tf", 2,
      "positions", ["position", 73, "position", 80],
      "df", 1,
      "tf-idf", 2.0],
     "good",
     ["tf", 1,
      "positions", ["position", 108],
      "df", 1,
      "tf-idf", 1.0],
     "had",
     ["tf", 2,
      "positions", ["position", 61, "position", 66],
      "df", 1,
      "tf-idf", 2.0],
     "heaven",
     ["tf", 1,
      "positions", ["position", 76],
      "df", 1,
      "tf-idf", 1.0],
     "hope",
     ["tf", 1,
      "positions", ["position", 53],
      "df", 1,
      "tf-idf", 1.0],
     "in",
     ["tf", 2,
      "positions", ["position", 85, "position", 112],
      "df", 1,
      "tf-idf", 2.0],
     "incredulity",
     ["tf", 1,
      "positions", ["position", 35],
      "df", 1,
      "tf-idf", 1.0],
     "insisted",
     ["tf", 1,
      "positions", ["position", 102],
      "df", 1,
      "tf-idf", 1.0],
     "it",
     ["tf", 10,
      "positions", ["position", 0, "position", 6, "position", 12,
                    "position", 18, "position", 24, "position", 30,
                    "position", 36, "position", 42, "position", 48,
                    "position", 54],
      "df", 1,
      "tf-idf", 10.0],
     "its",
     ["tf", 2,
      "positions", ["position", 99, "position", 104],
      "df", 1,
      "tf-idf", 2.0],
     "light",
     ["tf", 1,
      "positions", ["position", 41],
      "df", 1,
      "tf-idf", 1.0],
     "like",
     ["tf", 1,
      "positions", ["position", 92],
      "df", 1,
      "tf-idf", 1.0],
     "noisiest",
     ["tf", 1,
      "positions", ["position", 100],
      "df", 1,
      "tf-idf", 1.0],
     "nothing",
     ["tf", 1,
      "positions", ["position", 67],
      "df", 1,
      "tf-idf", 1.0],
     "of",
     ["tf", 12,
      "positions", ["position", 4, "position", 10, "position", 16,
                    "position", 22, "position", 28, "position", 34,
                    "position", 40, "position", 46, "position", 52,
                    "position", 58, "position", 98, "position", 116],
      "df", 1,
      "tf-idf", 12.0],
     "on",
     ["tf", 1,
      "positions", ["position", 103],
      "df", 1,
      "tf-idf", 1.0],
     "only",
     ["tf", 1,
      "positions", ["position", 118],
      "df", 1,
      "tf-idf", 1.0],
     "or",
     ["tf", 1,
      "positions", ["position", 109],
      "df", 1,
      "tf-idf", 1.0],
     "other",
     ["tf", 1,
      "positions", ["position", 83],
      "df", 1,
      "tf-idf", 1.0],
     "period",
     ["tf", 2,
      "positions", ["position", 88, "position", 95],
      "df", 1,
      "tf-idf", 2.0],
     "present",
     ["tf", 1,
      "positions", ["position", 94],
      "df", 1,
      "tf-idf", 1.0],
     "received",
     ["tf", 1,
      "positions", ["position", 106],
      "df", 1,
      "tf-idf", 1.0],
     "season",
     ["tf", 2,
      "positions", ["position", 39, "position", 45],
      "df", 1,
      "tf-idf", 2.0],
     "short",
     ["tf", 1,
      "positions", ["position", 86],
      "df", 1,
      "tf-idf", 1.0],
     "so",
     ["tf", 1,
      "positions", ["position", 90],
      "df", 1,
      "tf-idf", 1.0],
     "some",
     ["tf", 1,
      "positions", ["position", 97],
      "df", 1,
      "tf-idf", 1.0],
     "spring",
     ["tf", 1,
      "positions", ["position", 51],
      "df", 1,
      "tf-idf", 1.0],
     "superlative",
     ["tf", 1,
      "positions", ["position", 114],
      "df", 1,
      "tf-idf", 1.0],
     "that",
     ["tf", 1,
      "positions", ["position", 96],
      "df", 1,
      "tf-idf", 1.0],
     "the",
     ["tf", 14,
      "positions", ["position", 2, "position", 8, "position", 14,
                    "position", 20, "position", 26, "position", 32,
                    "position", 38, "position", 44, "position", 50,
                    "position", 56, "position", 82, "position", 87,
                    "position", 93, "position", 113],
      "df", 1,
      "tf-idf", 14.0],
     "times",
     ["tf", 2,
      "positions", ["position", 5, "position", 11],
      "df", 1,
      "tf-idf", 2.0],
     "to",
     ["tf", 1,
      "positions", ["position", 75],
      "df", 1,
      "tf-idf", 1.0],
     "us",
     ["tf", 2,
      "positions", ["position", 64, "position", 69],
      "df", 1,
      "tf-idf", 2.0],
     "was",
     ["tf", 11,
      "positions", ["position", 1, "position", 7, "position", 13,
                    "position", 19, "position", 25, "position", 31,
                    "position", 37, "position", 43, "position", 49,
                    "position", 55, "position", 89],
      "df", 1,
      "tf-idf", 11.0],
     "way",
     ["tf", 1,
      "positions", ["position", 84],
      "df", 1,
      "tf-idf", 1.0],
     "we",
     ["tf", 4,
      "positions", ["position", 60, "position", 65, "position", 70,
                    "position", 77],
      "df", 1,
      "tf-idf", 4.0],
     "were",
     ["tf", 2,
      "positions", ["position", 71, "position", 78],
      "df", 1,
      "tf-idf", 2.0],
     "winter",
     ["tf", 1,
      "positions", ["position", 57],
      "df", 1,
      "tf-idf", 1.0],
     "wisdom",
     ["tf", 1,
      "positions", ["position", 17],
      "df", 1,
      "tf-idf", 1.0],
     "worst",
     ["tf", 1,
      "positions", ["position", 9],
      "df", 1,
      "tf-idf", 1.0]
    ]
   ]
  ]
end
