
FactoryGirl.define do
  factory :solr_response, class: OpenStruct do
    skip_create

    response {
      { 'responseHeader'  =>
        { 'status' => 0,
          'QTime' => 5,
          'params' =>
          { 'q' => 'doi:10.5678/dickens',
            'defType' => 'lucene',
            'fl' => 'uid,doi,license,license_url,data_source,authors,title,journal,year,volume,number,pages,fulltext_url,fulltext',
            'wt' => 'ruby'
          }
        },
        'response' =>
        { 'numFound' => 1,
          'start' => 0,
          'docs'  =>
          [{ 'data_source' => 'Project Gutenberg',
             'license' => 'Public domain',
             'license_url' => 'http://www.gutenberg.org/license',
             'uid' => 'doi:10.5678/dickens',
             'doi' => '10.5678/dickens',
             'authors' => 'C. Dickens',
             'title' => 'A Tale of Two Cities',
             'year' => '1859',
             'volume' => '1',
             'number' => '1',
             'pages' => '1',
             'journal' => 'Actually a Novel',
             'fulltext' => 'It was the best of times,
      it was the worst of times,
      it was the age of wisdom,
      it was the age of foolishness,
      it was the epoch of belief,
      it was the epoch of incredulity,
      it was the season of Light,
      it was the season of Darkness,
      it was the spring of hope,
      it was the winter of despair,
      we had everything before us,
      we had nothing before us,
      we were all going direct to Heaven,
      we were all going direct the other way--
      in short, the period was so far like the present period, that some of
      its noisiest authorities insisted on its being received, for good or for
      evil, in the superlative degree of comparison only.'
          }]
        },
        'facet_counts' =>
        { 'facet_queries' =>
          { 'year:[* TO 1799]' => 0,
            'year:[1800 TO 1809]' => 0,
            'year:[1810 TO 1819]' => 0,
            'year:[1820 TO 1829]' => 0,
            'year:[1830 TO 1839]' => 0,
            'year:[1840 TO 1849]' => 0,
            'year:[1850 TO 1859]' => 1,
            'year:[1860 TO 1869]' => 0,
            'year:[1870 TO 1879]' => 0,
            'year:[1880 TO 1889]' => 0,
            'year:[1890 TO 1899]' => 0,
            'year:[1900 TO 1909]' => 0,
            'year:[1910 TO 1919]' => 0,
            'year:[1920 TO 1929]' => 0,
            'year:[1930 TO 1939]' => 0,
            'year:[1940 TO 1949]' => 0,
            'year:[1950 TO 1959]' => 0,
            'year:[1960 TO 1969]' => 0,
            'year:[1970 TO 1979]' => 0,
            'year:[1980 TO 1989]' => 0,
            'year:[1990 TO 1999]' => 0,
            'year:[2000 TO 2009]' => 0,
            'year:[2010 TO *]' => 1
          },
          'facet_fields' =>
          { 'authors_facet' =>
            ['C. Dickens', 1,
             '2009', 0,
             'A. Alegra Eroy-Reveles', 0,
             'A. Clinton White Jr', 0,
             'A. Clinton White Jr.', 0,
             'A. Desiree LaBeaud', 0,
             'A. Desirée LaBeaud', 0,
             'A. Diarrassouba', 0,
             'A. Keith Turner', 0,
             'A. Lee Willingham III', 0],
            'journal_facet' =>
            ['Actually a Novel', 1,
             'Gutenberg', 0,
             'PLoS Neglected Tropical Diseases', 0]
          },
          'facet_dates' => {},
          'facet_ranges' => {}
        },
        'termVectors' =>
          ['uniqueKeyFieldName', 'uid', 'doi:10.5678/dickens',
           ['uniqueKey', 'doi:10.5678/dickens', 'fulltext',
            ['age', ['tf', 2, 'positions', ['position', 15, 'position', 21],
                     'df', 735],
             'all', ['tf', 2, 'positions', ['position', 72, 'position', 79],
                     'df', 1464],
             'authorities', ['tf', 1, 'positions', ['position', 101],
                             'df', 156],
             'before', ['tf', 2, 'positions', ['position', 63, 'position', 68],
                        'df', 982],
             'being', ['tf', 1, 'positions', ['position', 105], 'df', 1016],
             'belief', ['tf', 1, 'positions', ['position', 29], 'df', 29],
             'best', ['tf', 1, 'positions', ['position', 3], 'df', 509],
             'comparison', ['tf', 1, 'positions', ['position', 117],
                            'df', 852],
             'darkness', ['tf', 1, 'positions', ['position', 47], 'df', 5],
             'degree', ['tf', 1, 'positions', ['position', 115], 'df', 427],
             'despair', ['tf', 1, 'positions', ['position', 59], 'df', 5],
             'direct', ['tf', 2, 'positions', ['position', 74, 'position', 81],
                        'df', 659],
             'epoch', ['tf', 2, 'positions', ['position', 27, 'position', 33],
                       'df', 3],
             'everything', ['tf', 1, 'positions', ['position', 62], 'df', 4],
             'evil', ['tf', 1, 'positions', ['position', 111], 'df', 5],
             'far', ['tf', 1, 'positions', ['position', 91], 'df', 473],
             'foolishness', ['tf', 1, 'positions', ['position', 23],
                             'df', 1],
             'for', ['tf', 2, 'positions', ['position', 107, 'position', 110],
                     'df', 1500],
             'going', ['tf', 2, 'positions', ['position', 73, 'position', 80],
                       'df', 78],
             'good', ['tf', 1, 'positions', ['position', 108], 'df', 480],
             'had', ['tf', 2, 'positions', ['position', 61, 'position', 66],
                     'df', 1435],
             'heaven', ['tf', 1, 'positions', ['position', 76], 'df', 1],
             'hope', ['tf', 1, 'positions', ['position', 53], 'df', 89],
             'in', ['tf', 2, 'positions', ['position', 85, 'position', 112],
                    'df', 1501],
             'incredulity', ['tf', 1, 'positions', ['position', 35],
                             'df', 1],
             'insisted', ['tf', 1, 'positions', ['position', 102], 'df', 3],
             'it', ['tf', 10, 'positions', ['position', 0, 'position', 6,
                                            'position', 12, 'position', 18,
                                            'position', 24, 'position', 30,
                                            'position', 36, 'position', 42,
                                            'position', 48, 'position', 54],
                    'df', 1486],
             'its', ['tf', 2, 'positions', ['position', 99, 'position', 104],
                     'df', 1220],
             'light', ['tf', 1, 'positions', ['position', 41], 'df', 551],
             'like', ['tf', 1, 'positions', ['position', 92], 'df', 837],
             'noisiest', ['tf', 1, 'positions', ['position', 100], 'df', 1],
             'nothing', ['tf', 1, 'positions', ['position', 67], 'df', 38],
             'of', ['tf', 12, 'positions', ['position', 4, 'position', 10,
                                            'position', 16, 'position', 22,
                                            'position', 28, 'position', 34,
                                            'position', 40, 'position', 46,
                                            'position', 52, 'position', 58,
                                            'position', 98, 'position', 116],
                    'df', 1501],
             'on', ['tf', 1, 'positions', ['position', 103], 'df', 1496],
             'only', ['tf', 1, 'positions', ['position', 118], 'df', 1422],
             'or', ['tf', 1, 'positions', ['position', 109], 'df', 1497],
             'other', ['tf', 1, 'positions', ['position', 83], 'df', 1479],
             'period', ['tf', 2, 'positions', ['position', 88, 'position', 95],
                        'df', 835],
             'present', ['tf', 1, 'positions', ['position', 94], 'df', 1233],
             'received', ['tf', 1, 'positions', ['position', 106], 'df', 673],
             'season', ['tf', 2, 'positions', ['position', 39, 'position', 45],
                        'df', 185],
             'short', ['tf', 1, 'positions', ['position', 86], 'df', 500],
             'so', ['tf', 1, 'positions', ['position', 90], 'df', 848],
             'some', ['tf', 1, 'positions', ['position', 97], 'df', 1314],
             'spring', ['tf', 1, 'positions', ['position', 51], 'df', 52],
             'superlative', ['tf', 1, 'positions', ['position', 114], 'df', 1],
             'that', ['tf', 1, 'positions', ['position', 96], 'df', 1500],
             'the', ['tf', 14, 'positions', ['position', 2, 'position', 8,
                                             'position', 14, 'position', 20,
                                             'position', 26, 'position', 32,
                                             'position', 38, 'position', 44,
                                             'position', 50, 'position', 56,
                                             'position', 82, 'position', 87,
                                             'position', 93, 'position', 113],
                     'df', 1500],
             'times', ['tf', 2, 'positions', ['position', 5, 'position', 11],
                       'df', 816],
             'to', ['tf', 1, 'positions', ['position', 75], 'df', 1500],
             'us', ['tf', 2, 'positions', ['position', 64, 'position', 69],
                    'df', 716],
             'was', ['tf', 11, 'positions', ['position', 1, 'position', 7,
                                             'position', 13, 'position', 19,
                                             'position', 25, 'position', 31,
                                             'position', 37, 'position', 43,
                                             'position', 49, 'position', 55,
                                             'position', 89],
                     'df', 1483],
             'way', ['tf', 1, 'positions', ['position', 84], 'df', 533],
             'we', ['tf', 4, 'positions', ['position', 60, 'position', 65,
                                           'position', 70, 'position', 77],
                    'df', 1447],
             'were', ['tf', 2, 'positions', ['position', 71, 'position', 78],
                      'df', 1463],
             'winter', ['tf', 1, 'positions', ['position', 57], 'df', 40],
             'wisdom', ['tf', 1, 'positions', ['position', 17], 'df', 5],
             'worst', ['tf', 1, 'positions', ['position', 9], 'df', 60]]]]
      }
    }
  end
end
